apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nservicecore

resources:
- namespace.yaml
- nlocalmodels-secret.yaml
- nlocalmodels-configmap.yaml
- nlocalmodels-deployment.yaml
- nlocalmodels-service.yaml
- nlocalmodels-apirule.yaml

commonLabels:
  app.kubernetes.io/name: nlocalmodels
  app.kubernetes.io/component: inference-service
  app.kubernetes.io/part-of: nservicecore

images:
- name: plturrell/nservices
  newTag: nLocalModels
